{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "API vs Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"url-worker\"}[1m])",
     "legendFormat": "{{Worker}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"url-api\"}[1m])",
     "legendFormat": "{{API}}"
    }
   ]
  },
  {
   "title": "Worker RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"url-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(api_latency_seconds_sum[1m]) / rate(api_latency_seconds_count[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "API Traffic Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}