apiVersion: apps/v1
kind: Deployment
metadata:
    name: url-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: url-api
    template:
        metadata:
            labels:
                app: url-api
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8000"
                prometheus.io/path: "/metrics"
        spec:
            containers:
                - name: url-api
                  image: andreimurica/url-api:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8000
                  resources:
                      requests:
                          cpu: "100m"
                  env:
                      - name: KAFKA_BOOTSTRAP_SERVERS
                        value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
    name: url-api-service
    annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
spec:
    type: NodePort
    selector:
        app: url-api
    ports:
        - port: 8000
          targetPort: 8000
          nodePort: 30001
