apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: url-api-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: url-api
    minReplicas: 1
    maxReplicas: 10
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 30
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 15
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 50
